#!/usr/bin/env python3
"""Print the optional renderer's pinned Unicode tables; no build-time downloads."""
import hashlib
import urllib.request

BASE = "https://www.unicode.org/Public/17.0.0/ucd/"


def read(path):
    data = urllib.request.urlopen(BASE + path, timeout=30).read()
    print("// " + path + " SHA-256: " + hashlib.sha256(data).hexdigest())
    return data.decode("utf-8")


def ranges(text, properties):
    result = []
    for line in text.splitlines():
        fields = line.split("#", 1)[0].strip().split(";")
        if len(fields) != 2 or fields[1].strip() not in properties:
            continue
        bounds = fields[0].strip().split("..")
        result.append((int(bounds[0], 16), int(bounds[-1], 16)))
    return result


def emit(name, entries):
    merged = []
    for lo, hi in sorted(entries):
        if merged and lo <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(hi, merged[-1][1]))
        else:
            merged.append((lo, hi))
    print("pub const " + name + " = [_][2]u21{")
    for lo, hi in merged:
        print(f"    .{{ 0x{lo:x}, 0x{hi:x} }},")
    print("};\n")


print("//! Generated by tools/generate_console_widths.py from Unicode 17.0.0.")
print("//! Used only by optional console presentation, never by either parser.")
license_text = urllib.request.urlopen("https://www.unicode.org/license.txt", timeout=30).read().decode("utf-8")
for line in license_text.splitlines():
    print("// " + line if line else "//")
wide = read("EastAsianWidth.txt")
category = read("extracted/DerivedGeneralCategory.txt")
print()
emit("wide", ranges(wide, {"W", "F"}))
emit("zero", ranges(category, {"Mn", "Me"}) + [(0x1160, 0x11FF), (0xD7B0, 0xD7FF)])
emit("control", ranges(category, {"Cc", "Cf", "Zl", "Zp"}))
